### ISSUE TITLE
`@othent/react-components` not working

### ISSUE THREAD

**Issue by ItsJackAnton** [Othent/KeyManagementService#35]
I am having issue using Othent to send messages to my process: I logged in using Othent in `localhost`, then clicked a button that sends the message with an `"Action"` tag of value `"Register"` to my process (ID = `"UMd0ZAHuOfc_X7ifaTTDTXIa1jBAhTy71r9GTiKl9n0"`).

I'm using Next.js and had to use a dynamic import to import the `OthentLogin` component, as otherwise I would not be able to use it, as Next.js would complain that it is require for that component to exist only on the client and "use client" was not enough.

Then, when I login with Othent or send messages I get this warning:

> [!WARNING]
> 
> Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.

This is the relevant code:

- [OthentLoginTsxComponent.txt](https://github.com/user-attachments/files/16764293/OthentLoginTsxComponent.txt)
- [RegistrationProcessLua.txt](https://github.com/user-attachments/files/16764295/RegistrationProcessLua.txt)

**Comment by Danziger** [comment]
Hi @ItsJackAnton. [`@othent/react-components`](https://github.com/Othent/react-components) hasn't been updated in a while and has just been deprecated.

You should instead use our SDK, [`@othent/kms`](https://github.com/Othent/KeyManagementService). It requires a few extra manual steps to integrate it in your project, but offers way more flexibility and resolves issues like that third-party cookie warning you got. You can find more about it at [docs.othent.io](https://docs.othent.io) and see it in action at [playground.othent.io](https://playground.othent.io).
